dataSources:
    ds_1:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/stock_sys_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
props:
    sql-show: true
