dataSources:
    df_1:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://43.163.230.128:3306/stock_sys_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ljx20001217
    ds_2021:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://43.163.230.128:3306/stock_db_2021?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ljx20001217
    ds_2022:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://43.163.230.128:3306/stock_db_2022?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ljx20001217
    ds_2023:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://43.163.230.128:3306/stock_db_2023?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ljx20001217
    ds_2024:
        driverClassName: com.mysql.cj.jdbc.Driver
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://43.163.230.128:3306/stock_db_2024?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ljx20001217

rules:
- !SHARDING
    tables:
        stock_block_rt_info:
            actualDataNodes: ds_${2021..2024}.stock_block_rt_info
            databaseStrategy:
                standard:
                    shardingColumn: cur_time
                    shardingAlgorithmName: algorithm4db
        stock_market_index_info:
            actualDataNodes: ds_${2021..2024}.stock_market_index_info
            databaseStrategy:
                standard:
                    shardingColumn: cur_time
                    shardingAlgorithmName: algorithm4db
        stock_outer_market_index_info:
            actualDataNodes: ds_${2021..2024}.stock_outer_market_index_info
            databaseStrategy:
                standard:
                    shardingColumn: cur_time
                    shardingAlgorithmName: algorithm4db
        stock_rt_info:
            actualDataNodes: ds_2021.stock_rt_info_${202101..202112},ds_2022.stock_rt_info_${202201..202212},ds_2023.stock_rt_info_${202301..202312},ds_2024.stock_rt_info_${202401..202412}
            databaseStrategy:
                standard:
                    shardingColumn: cur_time
                    shardingAlgorithmName: algorithm4db
            tableStrategy:
                standard:
                    shardingColumn: cur_time
                    shardingAlgorithmName: algorithm4StockRtInfoTable
    shardingAlgorithms:
        algorithm4db:
            type: CLASS_BASED
            props:
                strategy: standard
                algorithmClassName: com.jensen.stock.sharding.CommonShardingAlgorithm4Db
        algorithm4StockRtInfoTable:
            type: CLASS_BASED
            props:
                strategy: standard
                algorithmClassName: com.jensen.stock.sharding.ShardingAlgorithm4StockRtInfoTable
    broadcastTables:
        - stock_business
props:
    sql-show: true
